/* VÉLI SAFE — vélos, balades, villages viticoles, sites à visiter
   Chargé par index.html. Scripts classiques, pas de modules :
   le site doit pouvoir s'ouvrir par double-clic, sans serveur local. */

/* ===================== DONNÉES ===================== */
const BASE = [48.0794, 7.3585]; // Colmar centre

const VELOS = [
 {id:'ville', ico:'🚲', stock:14, demi:12, jour:18,
  nom:{fr:"Vélo de ville",en:"City bike",de:"Cityrad",es:"Bicicleta urbana",it:"City bike"},
  det:{fr:"7 vitesses, panier, cadre bas",en:"7 speeds, basket, step-through frame",de:"7 Gänge, Korb, tiefer Einstieg",es:"7 marchas, cesta, cuadro bajo",it:"7 rapporti, cesto, telaio basso"}},
 {id:'vae', ico:'⚡', stock:10, demi:25, jour:38,
  nom:{fr:"Vélo électrique",en:"Electric bike",de:"E-Bike",es:"Bicicleta eléctrica",it:"Bici elettrica"},
  det:{fr:"90 km d'autonomie, porte-bagages",en:"90 km range, rear rack",de:"90 km Reichweite, Gepäckträger",es:"90 km de autonomía, portaequipajes",it:"90 km di autonomia, portapacchi"}},
 {id:'enfant', ico:'🧒', stock:6, demi:8, jour:12,
  nom:{fr:"Vélo enfant",en:"Child's bike",de:"Kinderrad",es:"Bicicleta infantil",it:"Bici per bambini"},
  det:{fr:"20 ou 24 pouces, 6 à 11 ans",en:"20 or 24 inch, ages 6 to 11",de:"20 oder 24 Zoll, 6 bis 11 Jahre",es:"20 o 24 pulgadas, de 6 a 11 años",it:"20 o 24 pollici, da 6 a 11 anni"}},
 {id:'remorque', ico:'🛺', stock:4, demi:10, jour:16,
  nom:{fr:"Remorque enfant",en:"Child trailer",de:"Kinderanhänger",es:"Remolque infantil",it:"Rimorchio per bambini"},
  det:{fr:"2 places, s'adapte à tous nos vélos",en:"2 seats, fits all our bikes",de:"2 Plätze, passt an alle Räder",es:"2 plazas, compatible con todas",it:"2 posti, adattabile a tutte"}}
];

const BALADES = [
 {id:'egui', km:21, h:"2 h", lvl:'easy', couleur:'#7BC70A',
  nom:{fr:"Boucle d'Eguisheim",en:"Eguisheim loop",de:"Eguisheim-Runde",es:"Circuito de Eguisheim",it:"Anello di Eguisheim"},
  desc:{fr:"Le plus beau village de France en version courte, par Wettolsheim et Husseren.",
        en:"France's prettiest village, the short way, via Wettolsheim and Husseren.",
        de:"Frankreichs schönstes Dorf auf kurzem Weg über Wettolsheim und Husseren.",
        es:"El pueblo más bonito de Francia en versión corta, por Wettolsheim y Husseren.",
        it:"Il borgo più bello di Francia in versione breve, via Wettolsheim e Husseren."},
  pts:[[48.0794,7.3585],[48.0731,7.2933],[48.0578,7.2914],[48.0439,7.3067],[48.0356,7.2836],[48.0439,7.3067],[48.0560,7.3300],[48.0680,7.3450],[48.0794,7.3585]]},
 {id:'turck', km:26, h:"2 h 30", lvl:'easy', couleur:'#3F8F5C',
  nom:{fr:"Turckheim et les collines",en:"Turckheim and the hills",de:"Turckheim und die Hügel",es:"Turckheim y las colinas",it:"Turckheim e le colline"},
  desc:{fr:"Porte médiévale, grand cru Brand et retour par Ingersheim le long de la Fecht.",
        en:"Medieval gate, Brand grand cru and back through Ingersheim along the Fecht.",
        de:"Mittelalterliches Tor, Grand Cru Brand, zurück über Ingersheim entlang der Fecht.",
        es:"Puerta medieval, grand cru Brand y regreso por Ingersheim junto al Fecht.",
        it:"Porta medievale, grand cru Brand e ritorno da Ingersheim lungo il Fecht."},
  pts:[[48.0794,7.3585],[48.0776,7.3300],[48.0731,7.2933],[48.0856,7.2764],[48.0864,7.2703],[48.0914,7.2833],[48.0956,7.3033],[48.0880,7.3300],[48.0794,7.3585]]},
 {id:'kayser', km:44, h:"4 h", lvl:'mid', couleur:'#024F5F',
  nom:{fr:"Kaysersberg par la véloroute du vignoble",en:"Kaysersberg via the vineyard cycle route",de:"Kaysersberg über die Weinberg-Radroute",es:"Kaysersberg por la ruta ciclista del viñedo",it:"Kaysersberg lungo la ciclabile del vigneto"},
  desc:{fr:"Ammerschwihr, Kientzheim et le grand cru Schlossberg, classé dès 1975.",
        en:"Ammerschwihr, Kientzheim and the Schlossberg grand cru, classified back in 1975.",
        de:"Ammerschwihr, Kientzheim und der Grand Cru Schlossberg, klassifiziert seit 1975.",
        es:"Ammerschwihr, Kientzheim y el grand cru Schlossberg, clasificado desde 1975.",
        it:"Ammerschwihr, Kientzheim e il grand cru Schlossberg, classificato dal 1975."},
  pts:[[48.0794,7.3585],[48.0956,7.3033],[48.0914,7.2833],[48.1256,7.2789],[48.1381,7.2647],[48.1375,7.2825],[48.1381,7.2986],[48.1456,7.3050],[48.1531,7.3033],[48.1300,7.3300],[48.1050,7.3450],[48.0794,7.3585]]},
 {id:'riqu', km:57, h:"5 h", lvl:'hard', couleur:'#8A5A2B',
  nom:{fr:"Riquewihr et Ribeauvillé",en:"Riquewihr and Ribeauvillé",de:"Riquewihr und Ribeauvillé",es:"Riquewihr y Ribeauvillé",it:"Riquewihr e Ribeauvillé"},
  desc:{fr:"La perle du vignoble, Hunawihr et ses cigognes, vue sur le Haut-Kœnigsbourg.",
        en:"The pearl of the vineyard, Hunawihr and its storks, views to Haut-Kœnigsbourg.",
        de:"Die Perle des Weinbergs, Hunawihr mit seinen Störchen, Blick zur Hochkönigsburg.",
        es:"La perla del viñedo, Hunawihr y sus cigüeñas, vistas al Haut-Kœnigsbourg.",
        it:"La perla del vigneto, Hunawihr e le sue cicogne, vista sull'Haut-Kœnigsbourg."},
  pts:[[48.0794,7.3585],[48.0956,7.3033],[48.1256,7.2789],[48.1381,7.2986],[48.1531,7.3033],[48.1667,7.2975],[48.1806,7.3083],[48.1750,7.3128],[48.1947,7.3197],[48.1750,7.3400],[48.1450,7.3550],[48.1100,7.3600],[48.0794,7.3585]]},
 {id:'rhin', km:48, h:"4 h", lvl:'easy', couleur:'#2E7D9A',
  nom:{fr:"La plaine et Neuf-Brisach",en:"The plain and Neuf-Brisach",de:"Die Ebene und Neuf-Brisach",es:"La llanura y Neuf-Brisach",it:"La pianura e Neuf-Brisach"},
  desc:{fr:"Cent pour cent plat jusqu'à la citadelle de Vauban, classée à l'UNESCO, et au Rhin.",
        en:"Completely flat to Vauban's UNESCO-listed citadel and on to the Rhine.",
        de:"Vollkommen flach bis zur UNESCO-gelisteten Vauban-Zitadelle und zum Rhein.",
        es:"Totalmente llano hasta la ciudadela de Vauban, patrimonio UNESCO, y el Rin.",
        it:"Completamente pianeggiante fino alla cittadella di Vauban, patrimonio UNESCO, e al Reno."},
  pts:[[48.0794,7.3585],[48.0797,7.4014],[48.0653,7.4300],[48.0500,7.4800],[48.0364,7.5333],[48.0181,7.5286],[48.0181,7.5686],[48.0400,7.5000],[48.0600,7.4400],[48.0794,7.3585]]}
];

const VIGNOBLE = [
 {id:'eguisheim', pos:[48.0439,7.3067], km:7, gc:"Eichberg · Pfersigberg",
  nom:{fr:"Eguisheim",en:"Eguisheim",de:"Eguisheim",es:"Eguisheim",it:"Eguisheim"},
  desc:{fr:"Village circulaire élu Plus Beau Village de France, berceau du pape Léon IX.",
        en:"Circular village voted Most Beautiful Village of France, birthplace of Pope Leo IX.",
        de:"Runddorf, gewähltes schönstes Dorf Frankreichs, Geburtsort von Papst Leo IX.",
        es:"Pueblo circular elegido el más bello de Francia, cuna del papa León IX.",
        it:"Borgo circolare eletto più bel villaggio di Francia, patria di papa Leone IX."}},
 {id:'turckheim', pos:[48.0856,7.2764], km:8, gc:"Brand",
  nom:{fr:"Turckheim",en:"Turckheim",de:"Turckheim",es:"Turckheim",it:"Turckheim"},
  desc:{fr:"Trois portes fortifiées et le veilleur de nuit qui fait sa ronde en été.",
        en:"Three fortified gates and a night watchman still doing his rounds in summer.",
        de:"Drei Stadttore und der Nachtwächter, der im Sommer noch seine Runde dreht.",
        es:"Tres puertas fortificadas y el sereno que aún hace su ronda en verano.",
        it:"Tre porte fortificate e il guardiano notturno che d'estate fa ancora il giro."}},
 {id:'wintzenheim', pos:[48.0731,7.2933], km:5, gc:"Hengst",
  nom:{fr:"Wintzenheim",en:"Wintzenheim",de:"Wintzenheim",es:"Wintzenheim",it:"Wintzenheim"},
  desc:{fr:"Première étape depuis Colmar, à l'entrée de la vallée de Munster.",
        en:"First stop out of Colmar, at the mouth of the Munster valley.",
        de:"Erste Etappe ab Colmar, am Eingang zum Münstertal.",
        es:"Primera etapa desde Colmar, a la entrada del valle de Munster.",
        it:"Prima tappa da Colmar, all'ingresso della valle di Munster."}},
 {id:'wettolsheim', pos:[48.0578,7.2914], km:6, gc:"Steingrubler",
  nom:{fr:"Wettolsheim",en:"Wettolsheim",de:"Wettolsheim",es:"Wettolsheim",it:"Wettolsheim"},
  desc:{fr:"Village tranquille et sa réplique de la grotte de Lourdes.",
        en:"Quiet village with its replica of the Lourdes grotto.",
        de:"Ruhiges Dorf mit seiner Nachbildung der Grotte von Lourdes.",
        es:"Pueblo tranquilo con su réplica de la gruta de Lourdes.",
        it:"Villaggio tranquillo con la sua replica della grotta di Lourdes."}},
 {id:'kaysersberg', pos:[48.1381,7.2647], km:12, gc:"Schlossberg",
  nom:{fr:"Kaysersberg",en:"Kaysersberg",de:"Kaysersberg",es:"Kaysersberg",it:"Kaysersberg"},
  desc:{fr:"Cité impériale, château en ruine et pont fortifié sur la Weiss.",
        en:"Imperial town, ruined castle and fortified bridge over the Weiss.",
        de:"Reichsstadt, Burgruine und befestigte Brücke über die Weiss.",
        es:"Ciudad imperial, castillo en ruinas y puente fortificado sobre el Weiss.",
        it:"Città imperiale, castello in rovina e ponte fortificato sulla Weiss."}},
 {id:'riquewihr', pos:[48.1667,7.2975], km:14, gc:"Schoenenbourg · Sporen",
  nom:{fr:"Riquewihr",en:"Riquewihr",de:"Riquewihr",es:"Riquewihr",it:"Riquewihr"},
  desc:{fr:"Remparts intacts depuis le XVIᵉ siècle, surnommée la perle du vignoble.",
        en:"Ramparts untouched since the 16th century, known as the pearl of the vineyard.",
        de:"Seit dem 16. Jahrhundert unversehrte Mauern, die Perle des Weinbergs.",
        es:"Murallas intactas desde el siglo XVI, apodada la perla del viñedo.",
        it:"Mura intatte dal XVI secolo, soprannominata la perla del vigneto."}},
 {id:'hunawihr', pos:[48.1806,7.3083], km:16, gc:"Rosacker",
  nom:{fr:"Hunawihr",en:"Hunawihr",de:"Hunawihr",es:"Hunawihr",it:"Hunawihr"},
  desc:{fr:"Église fortifiée au milieu des vignes et centre de réintroduction des cigognes.",
        en:"Fortified church amid the vines and the stork reintroduction centre.",
        de:"Wehrkirche mitten in den Reben und das Storchenzentrum.",
        es:"Iglesia fortificada entre viñas y centro de reintroducción de cigüeñas.",
        it:"Chiesa fortificata tra le vigne e centro di reintroduzione delle cicogne."}},
 {id:'ribeauville', pos:[48.1947,7.3197], km:19, gc:"Kirchberg · Geisberg · Osterberg",
  nom:{fr:"Ribeauvillé",en:"Ribeauvillé",de:"Rappoltsweiler",es:"Ribeauvillé",it:"Ribeauvillé"},
  desc:{fr:"Trois châteaux au-dessus de la ville et trois grands crus sur ses coteaux.",
        en:"Three castles above the town and three grands crus on its slopes.",
        de:"Drei Burgen über der Stadt und drei Grands Crus an den Hängen.",
        es:"Tres castillos sobre la ciudad y tres grands crus en sus laderas.",
        it:"Tre castelli sopra la città e tre grands crus sui suoi pendii."}}
];

const ALSACE = [
 {id:'unterlinden', pos:[48.0797,7.3556], zoomable:true,
  nom:{fr:"Musée Unterlinden, Colmar",en:"Unterlinden Museum, Colmar",de:"Museum Unterlinden, Colmar",es:"Museo Unterlinden, Colmar",it:"Museo Unterlinden, Colmar"},
  desc:{fr:"Le retable d'Issenheim de Grünewald, dans un ancien couvent dominicain.",
        en:"Grünewald's Isenheim Altarpiece, inside a former Dominican convent.",
        de:"Grünewalds Isenheimer Altar in einem ehemaligen Dominikanerkloster.",
        es:"El retablo de Issenheim de Grünewald, en un antiguo convento dominico.",
        it:"La pala di Issenheim di Grünewald, in un ex convento domenicano."}},
 {id:'petitevenise', pos:[48.0723,7.3585],
  nom:{fr:"La Petite Venise, Colmar",en:"Little Venice, Colmar",de:"Klein-Venedig, Colmar",es:"La Pequeña Venecia, Colmar",it:"La Piccola Venezia, Colmar"},
  desc:{fr:"Le quartier des tanneurs et ses barques à fond plat sur la Lauch.",
        en:"The tanners' quarter and its flat-bottomed boats on the Lauch.",
        de:"Das Gerberviertel und die flachen Boote auf der Lauch.",
        es:"El barrio de los curtidores y sus barcas de fondo plano sobre el Lauch.",
        it:"Il quartiere dei conciatori e le barche a fondo piatto sulla Lauch."}},
 {id:'bartholdi', pos:[48.0776,7.3572],
  nom:{fr:"Musée Bartholdi, Colmar",en:"Bartholdi Museum, Colmar",de:"Bartholdi-Museum, Colmar",es:"Museo Bartholdi, Colmar",it:"Museo Bartholdi, Colmar"},
  desc:{fr:"La maison natale du sculpteur de la statue de la Liberté.",
        en:"The birthplace of the sculptor of the Statue of Liberty.",
        de:"Das Geburtshaus des Bildhauers der Freiheitsstatue.",
        es:"La casa natal del escultor de la Estatua de la Libertad.",
        it:"La casa natale dello scultore della Statua della Libertà."}},
 {id:'hautkoenig', pos:[48.2494,7.3444],
  nom:{fr:"Château du Haut-Kœnigsbourg",en:"Haut-Kœnigsbourg Castle",de:"Hochkönigsburg",es:"Castillo del Haut-Kœnigsbourg",it:"Castello dell'Haut-Kœnigsbourg"},
  desc:{fr:"À 757 m, panorama sur toute la plaine ; montée sévère, prévoyez la voiture ou le VAE.",
        en:"At 757 m, a view over the whole plain; a stiff climb, take the car or an e-bike.",
        de:"Auf 757 m, Blick über die ganze Ebene; steiler Anstieg, besser mit Auto oder E-Bike.",
        es:"A 757 m, panorámica de toda la llanura; subida dura, mejor en coche o eléctrica.",
        it:"A 757 m, panorama su tutta la pianura; salita dura, meglio in auto o e-bike."}},
 {id:'neufbrisach', pos:[48.0181,7.5286],
  nom:{fr:"Neuf-Brisach",en:"Neuf-Brisach",de:"Neu-Breisach",es:"Neuf-Brisach",it:"Neuf-Brisach"},
  desc:{fr:"Ville fortifiée en octogone par Vauban, inscrite à l'UNESCO, accessible à plat.",
        en:"Vauban's octagonal fortified town, UNESCO listed, reachable on flat roads.",
        de:"Vaubans achteckige Festungsstadt, UNESCO-Welterbe, flach erreichbar.",
        es:"Ciudad fortificada octogonal de Vauban, patrimonio UNESCO, accesible en llano.",
        it:"Città fortificata ottagonale di Vauban, patrimonio UNESCO, raggiungibile in piano."}},
 {id:'munster', pos:[48.0400,7.1372],
  nom:{fr:"Vallée de Munster",en:"Munster Valley",de:"Münstertal",es:"Valle de Munster",it:"Valle di Munster"},
  desc:{fr:"Fermes-auberges, marcaireries et le fromage qui porte le nom de la vallée.",
        en:"Mountain farm-inns, high pastures and the cheese named after the valley.",
        de:"Bauernhof-Gasthäuser, Bergweiden und der Käse, der das Tal berühmt macht.",
        es:"Granjas-albergue, pastos de altura y el queso que lleva el nombre del valle.",
        it:"Fattorie-locanda, alpeggi e il formaggio che porta il nome della valle."}},
 {id:'strasbourg', pos:[48.5734,7.7521],
  nom:{fr:"Strasbourg",en:"Strasbourg",de:"Straßburg",es:"Estrasburgo",it:"Strasburgo"},
  desc:{fr:"Cathédrale et quartier de la Petite France, à 35 minutes en TER depuis Colmar.",
        en:"Cathedral and the Petite France quarter, 35 minutes by regional train from Colmar.",
        de:"Münster und Viertel Petite France, 35 Minuten mit dem Regionalzug ab Colmar.",
        es:"Catedral y barrio de la Petite France, a 35 minutos en tren regional desde Colmar.",
        it:"Cattedrale e quartiere della Petite France, 35 minuti in treno regionale da Colmar."}},
 {id:'ecomusee', pos:[47.8656,7.3050],
  nom:{fr:"Écomusée d'Alsace, Ungersheim",en:"Alsace Eco-Museum, Ungersheim",de:"Ecomusée d'Alsace, Ungersheim",es:"Ecomuseo de Alsacia, Ungersheim",it:"Ecomuseo d'Alsazia, Ungersheim"},
  desc:{fr:"Un village alsacien reconstitué avec plus de septante maisons d'époque.",
        en:"A reconstructed Alsatian village with more than seventy period houses.",
        de:"Ein rekonstruiertes elsässisches Dorf mit über siebzig historischen Häusern.",
        es:"Un pueblo alsaciano reconstruido con más de setenta casas de época.",
        it:"Un villaggio alsaziano ricostruito con oltre settanta case d'epoca."}}
];
